version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis_queue
    ports:
      - "6379:6379"

  redis_commander:
    image: rediscommander/redis-commander
    container_name: redis_commander
    restart: always
    ports:
      - "9081:9081"
    environment:
      - REDIS_HOSTS=local:redis
    depends_on:
      - redis
